#! /bin/bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#check for install errors
systemctl --failed

#ask user if checks completed
echo -n "Were Checks Completed: "
read randovar

#install firewall
pacman -S --noconfirm nftables
systemctl enable nftables.service
systemctl start nftables.service
pacman -S --noconfirm firewalld
systemctl enable firewalld.service
systemctl start firewalld.service

#install Xorg
pacman -S --noconfirm xorg-server xorg-xinit

#install sddm
pacman -S --noconfirm sddm
systemctl enable sddm.service

#install Plasma
pacman -S --noconfirm plasma-desktop
pacman -S --noconfirm dolphin konsole kgpg kcalc kate partitionmanager ksystemlog gwenview spectacle git gnupg ntfs-3g

#install additional packages
echo "Type Additional Packages Seperated By A Space"
read addpackages
if [ -z "$addpackages" ]
then
      echo "No Additional Packages"
else
      pacman -S --noconfirm $packages
fi

#reboot
reboot
