#! /bin/bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#ask user if checks completed
echo -n "Were Checks Completed: "
stty echo
read randovar
stty echo
clear
echo randovar

#select hard disk
lsblk
if [ "$1" == "" ]; then
  echo "Enter Disk Name: /dev/"
  read harddisk
  echo $harddisk
  echo "Enter rando: "
  read rando
  echo $rando
else
  echo $1
fi

hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
clear
: ${hostname:?"hostname cannot be empty"}
