#! /bin/bash

#verify EUFI mode
ls /sys/firmware/efi/efivars

#set keyboard layout
loadkeys uk

#test network
ip link
ping -c 2 archlinux.org

#update system clock
timedatectl set-ntp true

#ask user if checks completed
echo -n "Were Checks Completed: "
stty echo
read randovar
stty echo
clear
echo randovar

#select hard disk
lsblk
if [ "$1" == "" ]; then
  echo "Enter Disk Name: /dev/"
  read harddisk
  echo $harddisk
  echo "Enter rando: "
  read rando
  echo $rando
else
  echo $1
fi
