#! /bin/bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

#check for install errors
systemctl --failed

#ask user if checks completed
echo -n "Were Checks Completed: "
read randovar

#enter username
echo -n "Enter Username: "
read username

#enter additional packages
echo "Type Additional Packages Seperated By A Space"
read addpackages

#install amd gpu drivers
pacman -S --noconfirm mesa mesa-utils lib32-mesa xf86-video-amdgpu vulkan-radeon lib32-vulkan-radeon libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau

#install Xorg
pacman -S --noconfirm xorg-server xorg-xinit

#install sddm
pacman -S --noconfirm sddm sddm-kcm
systemctl enable sddm.service

#install Plasma
pacman -S --noconfirm plasma-desktop
pacman -S --noconfirm kscreen plasma-disks plasma-firewall plasma-systemmonitor discover kinfocenter ksystemlog dolphin konsole powerdevil bluedevil kde-gtk-config breeze-gtk plasma-workspace-wallpapers

#install audio system
pacman -S --noconfirm pulseaudio plasma-pa
#jack2 lib32-jack2 jack_mixer cadence

#install commonly used packages
pacman -S --noconfirm kcalc partitionmanager gwenview spectacle gnupg git testdisk vim kate khotkeys blender neofetch man-db qbittorrent vlc bash-completion beets steam nicotine+

#install firewall
pacman -S --noconfirm nftables
systemctl enable nftables.service
systemctl start nftables.service
pacman -S --noconfirm firewalld
systemctl enable firewalld.service
systemctl start firewalld.service

#install openssh
pacman -S --noconfirm openssh
systemctl enable sshd

#install additional packages
if [ -z "$addpackages" ]
then
      echo "No Additional Packages"
else
      pacman -S --noconfirm $packages
fi

#Mount internal HDD's and SSD's
mkdir /home/$username/Drives
mkdir /home/$username/Drives/1TB
mkdir /home/$username/Drives/2TB
mkdir /home/$username/Drives/3TB
mkdir /home/$username/Drives/256GB
echo "
UUID=EE36076636072F61                       /home/volton/Drives/256GB   ntfs   defaults                                                                                                0 0
UUID=06AAF222AAF20DC5                       /home/volton/Drives/1TB     ntfs   defaults                                                                                                0 0
UUID=4670361717E3B507                       /home/volton/Drives/2TB     ntfs   defaults                                                                                                0 0
UUID=4EFE5B6BFE5B4A7B                       /home/volton/Drives/4TB     ntfs   defaults                                                                                                0 0
" >> /etc/fstab

#set mouse speed and acceleration in KDE
echo "[\$Version]
update_info=delete_cursor_old_default_size.upd:DeleteCursorOldDefaultSize,kcminputrc_fix_botched_5_21_0.upd:kcminputrc_fix_botched_5_21_0_pre,kcminputrc_fix_botched_5_21_0.upd:kcminputrc_fix_botched_5_21_0,kcminputrc_repeat.upd:kcminputrc_migrate_key_repeat

[Mouse]
XLbInptAccelProfileFlat=true
XLbInptPointerAcceleration=0.4

[Tmp]
update_info=delete_cursor_old_default_size.upd:DeleteCursorOldDefaultSize
" > /home/volton/.config/kcminputrc

#set keyboard layout in KDE
echo "[\$Version]
update_info=kxkb.upd:remove-empty-lists,kxkb.upd:add-back-resetoptions,kxkb_variants.upd:split-variants

[Layout]
LayoutList=gb
Use=true
" > /home/volton/.config/kxkbrc

#set double click to open file in KDE
echo "
[KDE]
SingleClick=false
" >> /home/volton/.config/kdeglobals

#setup KDE dolphin sidebar
cp /home/volton/Drives/1TB/Arch Setup/user-places.xbel /home/volton/.local/share/user-places.xbel

#sync all cache data to hdd
sync

#reboot
reboot
